- type: job
  id: TypanCargotech
  name: job-name-typan-cargotech
  playTimeTracker: JobTypanCargotech
  description: job-description-typan-cargotech
  startingGear: TypanCargotech
  icon: "JobIconTypanCargotech"
  supervisors: job-supervisors-typan-telecommunications-officer
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000
    - !type:OverallPlaytimeRequirement
      time: 3600
  access:
  - TypanCargo
  - TypanMaint
  - SyndicateAgent
  - TypanExternal
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skills # Corvax-Next-Skills
        skills:
        - ShuttleControl
        - Shooting
        - Butchering

- type: startingGear
  id: TypanCargotech
  equipment:
    eyes: ClothingEyesHudTypanDiagnostic
    ears: ClothingHeadsetAltSyndicate
    jumpsuit: ClothingUniformJumpsuitTypanCargotech
    shoes: ClothingShoesBootsCombatSyndie
    id: SyndiPDACargo
    outerClothing: ClothingOuterCoatLetterman

