- type: job
  id: TypanPatrol
  name: job-name-typan-patrol
  playTimeTracker: TypanPatrol
  description: job-description-typan-patrol
  startingGear: TypanPatrol
  icon: "JobIconSyndicateOfficer"
  supervisors: job-supervisors-typan-syndicate
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Typan
      time: 36000
    - !type:AgeRequirement
      requiredAge: 26
  access:
  - TypanArmory
  - TypanCommand
  - TypanCommunicationsOfficer
  - TypanEngineering
  - TypanMaint
  - TypanProtection
  - TypanScience
  - TypanService
  - TypanVault
  - TypanExternal
  - SyndicateAgent
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skills # Corvax-Next-Skills
        skills:
        - ShuttleControl
        - Shooting

- type: startingGear
  id: TypanPatrol
  equipment:
    ears: ClothingHeadsetAltSyndicate
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    id: SyndiPDAOff
    head: ClothingHeadHatSyndie
    pocket1: WeaponPistolViper
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudTypanPatrol
    outerClothing: ClothingOuterWinterSyndieCapArmored
  storage:
    back:
    - MagazinePistolIncendiary
    - MagazinePistolIncendiary
    - Zipties
    - Zipties

